version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: medisync-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootadmin
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: