spring:
    application:
        name: identity-service
    data: 
        mongodb:
            uri: mongodb://rootadmin:rootpassword@localhost:27017/medisync_identity?authSource=admin

server:
    port: 8081    
